project_id = "yogznoljqhunmvvekovv"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-daily-followup-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/send-daily-followup-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-daily-followup-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-daily-followup-reminders/*.html" ]
